#!/usr/bin/env bash
# Runs ON the Lightsail instance, invoked remotely by GitHub Actions via
# `aws ssm send-command` (CD6). Downloads freshly-built artifacts from short-lived S3 presigned
# URLs (generated by the GitHub Actions job, which holds real S3 permissions via OIDC) and
# restarts the affected services.
#
# Deliberately does NOT use the AWS CLI on the instance side: Lightsail instances have their own
# baked-in metadata-vended identity (AmazonLightsailInstanceRole, in AWS's own account) that takes
# priority over any hybrid-activation role in the default credential chain, so an `aws s3 cp` here
# would silently try to auth as the wrong identity. Presigned URLs sidestep that entirely — the
# instance needs nothing but curl.
#
# WEB_URL / API_URL are NOT defined in this file — the CI job prepends two `WEB_URL='...'` /
# `API_URL='...'` lines ahead of this script's content at deploy time, built via jq's `@sh` filter
# (safe for arbitrary content, including the many `&` characters in a presigned URL's query
# string). An earlier text-substitution approach corrupted the URL for exactly that reason.
#
# Does NOT touch /opt/ueq/api/api.env (holds UEQ_DB_CONNSTRING) — that file is never part of the
# published API output, so a plain overwrite never clobbers it. Same holds for
# /opt/ueq/gameserver/gameserver.env once 6.2's gameserver deploy below is active.
#
# GAMESERVER_URL (6.2) is presigned the same way as WEB_URL/API_URL, but the object it points at
# is uploaded to S3 manually/locally (the Unity Linux Dedicated Server build has no CI — DH7), not
# by this workflow. Until that first manual upload happens, the presigned URL 404s — deliberately
# NOT fatal (see the "Deploying gameserver" block below, which treats a failed download as a skip,
# not an error), so wiring this in ahead of the first real upload can't break the existing web/api
# deploy.
#
# The gameserver artifact is a .tar.gz, not a .zip like web/api — found the hard way that
# PowerShell's `Compress-Archive` (used to package the build on the Windows machine that produces
# it, since there's no Unity CI) can write backslash path separators inside the zip, which Linux's
# `unzip` can't parse for nested folders (e.g. `Ueq_Data/`). `tar` has no such ambiguity and ships
# natively on both Windows 10+ and Linux.
#
# CLIENT_URL/VERSION_URL (6.4): this box never extracts client.zip itself — it just stores the raw
# bytes for Caddy's file_server to hand to a Windows machine, where the launcher (not Linux unzip)
# does the extracting. So the Compress-Archive backslash-path issue above doesn't apply here; a
# plain .zip is fine. Same "presign always succeeds, deploy.sh treats a 404 as a skip" pattern as
# GAMESERVER_URL, for the same reason (no CI build for either).
set -euo pipefail

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

# Downloads $1 to $2. Unlike `curl -f`, this surfaces the actual response body on a non-2xx
# status (S3 error responses are small XML with a specific <Code>/<Message> — worth seeing
# instead of curl's generic "error 22" when something's wrong with the presigned URL).
download() {
  local url="$1" out="$2" status
  status=$(curl -sSL -o "$out" -w '%{http_code}' "$url")
  if [ "$status" -lt 200 ] || [ "$status" -ge 300 ]; then
    echo "Download failed (HTTP $status) for $out:" >&2
    cat "$out" >&2
    return 1
  fi
}

echo "== Deploying web =="
download "$WEB_URL" "${WORKDIR}/web.zip"
sudo rm -rf /var/www/ueq-web
sudo mkdir -p /var/www/ueq-web
sudo unzip -q -o "${WORKDIR}/web.zip" -d /var/www/ueq-web

echo "== Deploying api =="
download "$API_URL" "${WORKDIR}/api.zip"
sudo unzip -q -o "${WORKDIR}/api.zip" -d /opt/ueq/api

echo "== Restarting services =="
sudo systemctl restart ueq-api.service
sudo systemctl reload caddy

echo "== Deploying gameserver =="
if [ -n "${GAMESERVER_URL:-}" ]; then
  if download "$GAMESERVER_URL" "${WORKDIR}/gameserver.tar.gz"; then
    sudo mkdir -p /opt/ueq/gameserver
    sudo tar xzf "${WORKDIR}/gameserver.tar.gz" -C /opt/ueq/gameserver
    sudo chmod +x /opt/ueq/gameserver/Ueq.x86_64
    sudo systemctl restart ueq-gameserver.service
  else
    echo "Gameserver artifact not available yet (not uploaded to S3 for the first time?) — skipping, not failing the deploy." >&2
  fi
else
  echo "GAMESERVER_URL not set — skipping gameserver deploy."
fi

echo "== Deploying client download artifacts =="
sudo mkdir -p /var/www/ueq-downloads
if [ -n "${CLIENT_URL:-}" ]; then
  if download "$CLIENT_URL" "/tmp/UeqClient.zip"; then
    sudo mv /tmp/UeqClient.zip /var/www/ueq-downloads/UeqClient.zip
  else
    echo "Client artifact not available yet — skipping, not failing the deploy." >&2
  fi
else
  echo "CLIENT_URL not set — skipping."
fi
if [ -n "${VERSION_URL:-}" ]; then
  if download "$VERSION_URL" "/tmp/version.txt"; then
    sudo mv /tmp/version.txt /var/www/ueq-downloads/version.txt
  else
    echo "version.txt not available yet — skipping, not failing the deploy." >&2
  fi
else
  echo "VERSION_URL not set — skipping."
fi
# LAUNCHER_URL: the devplan originally called this a rare one-off not worth wiring in — turned out
# hand-pasting a long presigned URL into the Lightsail browser-SSH console is fragile (it corrupts
# long lines with stray whitespace at display-wrap points, a known issue with that console), so
# routing it through this already-reliable pipeline instead is simpler than working around that.
if [ -n "${LAUNCHER_URL:-}" ]; then
  if download "$LAUNCHER_URL" "/tmp/UeqLauncher.exe"; then
    sudo mv /tmp/UeqLauncher.exe /var/www/ueq-downloads/UeqLauncher.exe
  else
    echo "Launcher artifact not available yet — skipping, not failing the deploy." >&2
  fi
else
  echo "LAUNCHER_URL not set — skipping."
fi

echo "== Deploy complete =="
