#!/usr/bin/env bash
# Runs ON the Lightsail instance, invoked remotely by GitHub Actions via
# `aws ssm send-command` (CD6). Downloads freshly-built artifacts from short-lived S3 presigned
# URLs (generated by the GitHub Actions job, which holds real S3 permissions via OIDC) and
# restarts the affected services.
#
# Deliberately does NOT use the AWS CLI on the instance side: Lightsail instances have their own
# baked-in metadata-vended identity (AmazonLightsailInstanceRole, in AWS's own account) that takes
# priority over any hybrid-activation role in the default credential chain, so an `aws s3 cp` here
# would silently try to auth as the wrong identity. Presigned URLs sidestep that entirely — the
# instance needs nothing but curl. WEB_URL / API_URL are substituted in by the CI job at deploy
# time (short-lived, ~10-minute links, not secrets worth persisting).
#
# Does NOT touch /opt/ueq/api/api.env (holds UEQ_DB_CONNSTRING) — that file is never part of the
# published API output, so a plain overwrite never clobbers it.
set -euo pipefail

WEB_URL="REPLACE_ME_WEB_URL"
API_URL="REPLACE_ME_API_URL"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

# Downloads $1 to $2. Unlike `curl -f`, this surfaces the actual response body on a non-2xx
# status (S3 error responses are small XML with a specific <Code>/<Message> — worth seeing
# instead of curl's generic "error 22" when something's wrong with the presigned URL).
download() {
  local url="$1" out="$2" status
  status=$(curl -sSL -o "$out" -w '%{http_code}' "$url")
  if [ "$status" -lt 200 ] || [ "$status" -ge 300 ]; then
    echo "Download failed (HTTP $status) for $out:" >&2
    cat "$out" >&2
    return 1
  fi
}

echo "DEBUG received WEB_URL (len ${#WEB_URL}): $WEB_URL"

echo "== Deploying web =="
download "$WEB_URL" "${WORKDIR}/web.zip"
sudo rm -rf /var/www/ueq-web
sudo mkdir -p /var/www/ueq-web
sudo unzip -q -o "${WORKDIR}/web.zip" -d /var/www/ueq-web

echo "== Deploying api =="
download "$API_URL" "${WORKDIR}/api.zip"
sudo unzip -q -o "${WORKDIR}/api.zip" -d /opt/ueq/api

echo "== Restarting services =="
sudo systemctl restart ueq-api.service
sudo systemctl reload caddy

echo "== Deploy complete =="
